services:
  # Python 后端 (负责逻辑)
  media-server:
    build: .
    container_name: my_media_backend
    restart: always
    # 注意：这里不再对外暴露端口，只暴露给内部网络
    expose: 
      - "8000"
    volumes:
      - /home/aqww/spider/Content:/app/content
    environment:
      - MAX_WORKERS=4

  # Nginx 前端 (负责视频流 + 转发 API)
  nginx:
    image: nginx:alpine
    container_name: my_media_nginx
    restart: always
    ports:
      # 对外暴露 9000 端口（你可以改成 80）
      - "9000:80"
    volumes:
      # 1. 挂载配置文件
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # 2. 关键：Nginx 也必须能看到视频文件，路径对应 nginx.conf 里的 alias
      - /home/aqww/spider/Content:/usr/share/nginx/html/content:ro
    depends_on:
      - media-server